on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Packages
        run: sudo apt-get update -yq

      - name: Install dependencies
        run: sudo apt-get install -yq --no-install-recommends libudev-dev libasound2-dev libxcb-composite0-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.0

  format:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Install fmt
        run: rustup component add rustfmt
      - name: fmt
        run: cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: check
        run: cargo check

  clippy:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Install clippy  
        run: rustup component add clippy
      
      - name: run clippy
        run: cargo clippy -- -D warnings

  doc:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: docs
        run: cargo doc --no-deps --workspace
        env:
          RUSTDOCFLAGS: -D warnings
    
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: test
        run: cargo test
